import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import './globals.css'
import { Analytics } from '@vercel/analytics/react';

export const metadata = {
  title: 'Illiassou Issoufou A. H',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navbar />
        </header>
        <main>{children}</main>
        <Footer />
        <Analytics />
      </body>
    </html>
  )
}
